// Copyright 2019-2020 Enseada authors
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/v1beta1/acl_api.proto

package authv1beta1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request body to list all available ACL permissions.
type ListPermissionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPermissionsRequest) Reset()         { *m = ListPermissionsRequest{} }
func (m *ListPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPermissionsRequest) ProtoMessage()    {}
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e29e90e62174e322, []int{0}
}

func (m *ListPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPermissionsRequest.Unmarshal(m, b)
}
func (m *ListPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPermissionsRequest.Marshal(b, m, deterministic)
}
func (m *ListPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPermissionsRequest.Merge(m, src)
}
func (m *ListPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPermissionsRequest.Size(m)
}
func (m *ListPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPermissionsRequest proto.InternalMessageInfo

// Response body with a list of all available ACL permissions.
type ListPermissionsResponse struct {
	Permissions          []*AclPermission `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListPermissionsResponse) Reset()         { *m = ListPermissionsResponse{} }
func (m *ListPermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPermissionsResponse) ProtoMessage()    {}
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e29e90e62174e322, []int{1}
}

func (m *ListPermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPermissionsResponse.Unmarshal(m, b)
}
func (m *ListPermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPermissionsResponse.Marshal(b, m, deterministic)
}
func (m *ListPermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPermissionsResponse.Merge(m, src)
}
func (m *ListPermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPermissionsResponse.Size(m)
}
func (m *ListPermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPermissionsResponse proto.InternalMessageInfo

func (m *ListPermissionsResponse) GetPermissions() []*AclPermission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

// Request body to add a new ACL permission.
type AddPermissionRequest struct {
	// The permission to add. Required.
	Permission           *AclPermission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddPermissionRequest) Reset()         { *m = AddPermissionRequest{} }
func (m *AddPermissionRequest) String() string { return proto.CompactTextString(m) }
func (*AddPermissionRequest) ProtoMessage()    {}
func (*AddPermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e29e90e62174e322, []int{2}
}

func (m *AddPermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPermissionRequest.Unmarshal(m, b)
}
func (m *AddPermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPermissionRequest.Marshal(b, m, deterministic)
}
func (m *AddPermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPermissionRequest.Merge(m, src)
}
func (m *AddPermissionRequest) XXX_Size() int {
	return xxx_messageInfo_AddPermissionRequest.Size(m)
}
func (m *AddPermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPermissionRequest proto.InternalMessageInfo

func (m *AddPermissionRequest) GetPermission() *AclPermission {
	if m != nil {
		return m.Permission
	}
	return nil
}

// Response body with the newly added ACL permission.
type AddPermissionResponse struct {
	Permission           *AclPermission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddPermissionResponse) Reset()         { *m = AddPermissionResponse{} }
func (m *AddPermissionResponse) String() string { return proto.CompactTextString(m) }
func (*AddPermissionResponse) ProtoMessage()    {}
func (*AddPermissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e29e90e62174e322, []int{3}
}

func (m *AddPermissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPermissionResponse.Unmarshal(m, b)
}
func (m *AddPermissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPermissionResponse.Marshal(b, m, deterministic)
}
func (m *AddPermissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPermissionResponse.Merge(m, src)
}
func (m *AddPermissionResponse) XXX_Size() int {
	return xxx_messageInfo_AddPermissionResponse.Size(m)
}
func (m *AddPermissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPermissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPermissionResponse proto.InternalMessageInfo

func (m *AddPermissionResponse) GetPermission() *AclPermission {
	if m != nil {
		return m.Permission
	}
	return nil
}

// Request body to delete an ACL permission.
type DeletePermissionRequest struct {
	// The permission to delete. Required.
	Permission           *AclPermission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeletePermissionRequest) Reset()         { *m = DeletePermissionRequest{} }
func (m *DeletePermissionRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePermissionRequest) ProtoMessage()    {}
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e29e90e62174e322, []int{4}
}

func (m *DeletePermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePermissionRequest.Unmarshal(m, b)
}
func (m *DeletePermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePermissionRequest.Marshal(b, m, deterministic)
}
func (m *DeletePermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePermissionRequest.Merge(m, src)
}
func (m *DeletePermissionRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePermissionRequest.Size(m)
}
func (m *DeletePermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePermissionRequest proto.InternalMessageInfo

func (m *DeletePermissionRequest) GetPermission() *AclPermission {
	if m != nil {
		return m.Permission
	}
	return nil
}

// Response body with the deleted ACL permission.
type DeletePermissionResponse struct {
	Permission           *AclPermission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeletePermissionResponse) Reset()         { *m = DeletePermissionResponse{} }
func (m *DeletePermissionResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePermissionResponse) ProtoMessage()    {}
func (*DeletePermissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e29e90e62174e322, []int{5}
}

func (m *DeletePermissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePermissionResponse.Unmarshal(m, b)
}
func (m *DeletePermissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePermissionResponse.Marshal(b, m, deterministic)
}
func (m *DeletePermissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePermissionResponse.Merge(m, src)
}
func (m *DeletePermissionResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePermissionResponse.Size(m)
}
func (m *DeletePermissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePermissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePermissionResponse proto.InternalMessageInfo

func (m *DeletePermissionResponse) GetPermission() *AclPermission {
	if m != nil {
		return m.Permission
	}
	return nil
}

func init() {
	proto.RegisterType((*ListPermissionsRequest)(nil), "auth.v1beta1.ListPermissionsRequest")
	proto.RegisterType((*ListPermissionsResponse)(nil), "auth.v1beta1.ListPermissionsResponse")
	proto.RegisterType((*AddPermissionRequest)(nil), "auth.v1beta1.AddPermissionRequest")
	proto.RegisterType((*AddPermissionResponse)(nil), "auth.v1beta1.AddPermissionResponse")
	proto.RegisterType((*DeletePermissionRequest)(nil), "auth.v1beta1.DeletePermissionRequest")
	proto.RegisterType((*DeletePermissionResponse)(nil), "auth.v1beta1.DeletePermissionResponse")
}

func init() { proto.RegisterFile("auth/v1beta1/acl_api.proto", fileDescriptor_e29e90e62174e322) }

var fileDescriptor_e29e90e62174e322 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcb, 0x4a, 0xc3, 0x40,
	0x14, 0x25, 0x29, 0x74, 0x71, 0x53, 0x51, 0x06, 0x35, 0x21, 0x6e, 0x6a, 0x7c, 0xe0, 0x2a, 0x25,
	0x75, 0x29, 0x2e, 0x26, 0xb8, 0x11, 0x5c, 0x84, 0x2a, 0x35, 0x8a, 0x28, 0xd3, 0x64, 0xc0, 0x81,
	0x98, 0xc4, 0xce, 0xd4, 0x0f, 0x12, 0xdc, 0xf8, 0x29, 0x7e, 0x95, 0x8c, 0x19, 0xcc, 0xab, 0x9a,
	0x45, 0xbb, 0x9c, 0x39, 0x8f, 0x7b, 0xb8, 0x87, 0x0b, 0x36, 0x59, 0x88, 0xe7, 0xd1, 0x9b, 0x37,
	0xa3, 0x82, 0x78, 0x23, 0x12, 0x25, 0x4f, 0x24, 0x67, 0x6e, 0x3e, 0xcf, 0x44, 0x86, 0x06, 0x12,
	0x73, 0x15, 0x66, 0xef, 0xb7, 0x98, 0x39, 0x9d, 0xbf, 0x30, 0xce, 0x59, 0x96, 0x16, 0x02, 0xc7,
	0x82, 0xdd, 0x2b, 0xc6, 0x45, 0xf0, 0xfb, 0xcf, 0x27, 0xf4, 0x75, 0x41, 0xb9, 0x70, 0x42, 0x30,
	0x5b, 0x08, 0xcf, 0xb3, 0x94, 0x53, 0x74, 0x0e, 0x46, 0x69, 0xc4, 0x2d, 0x6d, 0xd8, 0x3b, 0x31,
	0xc6, 0x7b, 0x6e, 0x75, 0xb6, 0x8b, 0xa3, 0xa4, 0x94, 0x4e, 0xaa, 0x7c, 0xe7, 0x1a, 0xb6, 0x71,
	0x1c, 0x57, 0xd0, 0x62, 0x22, 0x3a, 0x03, 0x28, 0x69, 0x96, 0x36, 0xd4, 0xba, 0x5c, 0x2b, 0x74,
	0xe7, 0x06, 0x76, 0x1a, 0xa6, 0x2a, 0xec, 0x4a, 0xae, 0x53, 0x30, 0x2f, 0x68, 0x42, 0x05, 0x5d,
	0x73, 0xda, 0x5b, 0xb0, 0xda, 0xbe, 0x6b, 0x08, 0x3c, 0xfe, 0xd0, 0xa1, 0x8f, 0xa3, 0x04, 0x07,
	0x97, 0xe8, 0x11, 0x36, 0x1b, 0x05, 0xa2, 0xc3, 0xba, 0xcd, 0xf2, 0xe6, 0xed, 0xa3, 0x0e, 0x96,
	0xca, 0x19, 0xc2, 0x46, 0x6d, 0xe3, 0xc8, 0x69, 0x84, 0x5c, 0xd2, 0xb1, 0x7d, 0xf0, 0x2f, 0x47,
	0x39, 0x13, 0xd8, 0x6a, 0x6e, 0x07, 0x35, 0x42, 0xfd, 0xd1, 0x8a, 0x7d, 0xdc, 0x45, 0x2b, 0x46,
	0xf8, 0x77, 0x60, 0xb2, 0xcc, 0xa5, 0x29, 0xa7, 0x24, 0x26, 0x35, 0x8d, 0x6f, 0xc8, 0xfd, 0xe5,
	0x2c, 0x90, 0xf7, 0x11, 0x68, 0xf7, 0x86, 0x04, 0x15, 0xf6, 0xae, 0xf7, 0x70, 0x18, 0x7e, 0xea,
	0x03, 0x2c, 0x05, 0x53, 0xcf, 0x97, 0x9f, 0x5f, 0xc5, 0xf3, 0x41, 0x3d, 0x67, 0xfd, 0x9f, 0xcb,
	0x3a, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x7a, 0xaf, 0xb4, 0xa8, 0x03, 0x00, 0x00,
}
