// Copyright 2019-2020 Enseada authors
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/v1beta1/acl_permission.proto

package authv1beta1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Single ACL permission.
type AclPermission struct {
	// The subject of the permission. Required.
	Sub string `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	// The subject of the permission. Required. Must be a valid Enseada GUID.
	Obj string `protobuf:"bytes,2,opt,name=obj,proto3" json:"obj,omitempty"`
	// The action of the permission. Required.
	Act                  string   `protobuf:"bytes,3,opt,name=act,proto3" json:"act,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AclPermission) Reset()         { *m = AclPermission{} }
func (m *AclPermission) String() string { return proto.CompactTextString(m) }
func (*AclPermission) ProtoMessage()    {}
func (*AclPermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e03521deb49ca5c, []int{0}
}

func (m *AclPermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AclPermission.Unmarshal(m, b)
}
func (m *AclPermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AclPermission.Marshal(b, m, deterministic)
}
func (m *AclPermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AclPermission.Merge(m, src)
}
func (m *AclPermission) XXX_Size() int {
	return xxx_messageInfo_AclPermission.Size(m)
}
func (m *AclPermission) XXX_DiscardUnknown() {
	xxx_messageInfo_AclPermission.DiscardUnknown(m)
}

var xxx_messageInfo_AclPermission proto.InternalMessageInfo

func (m *AclPermission) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *AclPermission) GetObj() string {
	if m != nil {
		return m.Obj
	}
	return ""
}

func (m *AclPermission) GetAct() string {
	if m != nil {
		return m.Act
	}
	return ""
}

func init() {
	proto.RegisterType((*AclPermission)(nil), "auth.v1beta1.AclPermission")
}

func init() { proto.RegisterFile("auth/v1beta1/acl_permission.proto", fileDescriptor_0e03521deb49ca5c) }

var fileDescriptor_0e03521deb49ca5c = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4c, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xd4, 0x4f, 0x4c, 0xce, 0x89, 0x2f, 0x48, 0x2d,
	0xca, 0xcd, 0x2c, 0x2e, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01,
	0x29, 0xd1, 0x83, 0x2a, 0x51, 0x72, 0xe5, 0xe2, 0x75, 0x4c, 0xce, 0x09, 0x80, 0x2b, 0x12, 0x12,
	0xe0, 0x62, 0x2e, 0x2e, 0x4d, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x41, 0x22,
	0xf9, 0x49, 0x59, 0x12, 0x4c, 0x10, 0x91, 0xfc, 0xa4, 0x2c, 0x90, 0x48, 0x62, 0x72, 0x89, 0x04,
	0x33, 0x44, 0x24, 0x31, 0xb9, 0xc4, 0x29, 0x81, 0x4b, 0x3c, 0x33, 0x5f, 0x2f, 0x35, 0xaf, 0x38,
	0x35, 0x31, 0x25, 0x51, 0x0f, 0xd9, 0x06, 0x27, 0x21, 0x14, 0xf3, 0x03, 0x40, 0x6e, 0x08, 0x60,
	0x8c, 0xe2, 0x06, 0xa9, 0x81, 0x2a, 0x59, 0xc4, 0xc4, 0xec, 0x18, 0x11, 0xb1, 0x8a, 0x89, 0xc7,
	0x11, 0xa4, 0x2f, 0xcc, 0xd0, 0x09, 0x24, 0x78, 0x0a, 0xc2, 0x8d, 0x81, 0x72, 0x93, 0xd8, 0xc0,
	0xae, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x47, 0xce, 0xc6, 0x7b, 0xe2, 0x00, 0x00, 0x00,
}
