// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/v1beta1/acl_api.proto

package authv1beta1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request body to list all available ACL rules.
type ListRulesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRulesRequest) Reset()         { *m = ListRulesRequest{} }
func (m *ListRulesRequest) String() string { return proto.CompactTextString(m) }
func (*ListRulesRequest) ProtoMessage()    {}
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e29e90e62174e322, []int{0}
}

func (m *ListRulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRulesRequest.Unmarshal(m, b)
}
func (m *ListRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRulesRequest.Marshal(b, m, deterministic)
}
func (m *ListRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRulesRequest.Merge(m, src)
}
func (m *ListRulesRequest) XXX_Size() int {
	return xxx_messageInfo_ListRulesRequest.Size(m)
}
func (m *ListRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRulesRequest proto.InternalMessageInfo

// Response body with a list of all available ACL rules.
type ListRulesResponse struct {
	Rules                []*AclRule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListRulesResponse) Reset()         { *m = ListRulesResponse{} }
func (m *ListRulesResponse) String() string { return proto.CompactTextString(m) }
func (*ListRulesResponse) ProtoMessage()    {}
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e29e90e62174e322, []int{1}
}

func (m *ListRulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRulesResponse.Unmarshal(m, b)
}
func (m *ListRulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRulesResponse.Marshal(b, m, deterministic)
}
func (m *ListRulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRulesResponse.Merge(m, src)
}
func (m *ListRulesResponse) XXX_Size() int {
	return xxx_messageInfo_ListRulesResponse.Size(m)
}
func (m *ListRulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRulesResponse proto.InternalMessageInfo

func (m *ListRulesResponse) GetRules() []*AclRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

// Request body to add a new ACL rule.
type AddRuleRequest struct {
	// The rule to add. Required.
	Rule                 *AclRule `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRuleRequest) Reset()         { *m = AddRuleRequest{} }
func (m *AddRuleRequest) String() string { return proto.CompactTextString(m) }
func (*AddRuleRequest) ProtoMessage()    {}
func (*AddRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e29e90e62174e322, []int{2}
}

func (m *AddRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRuleRequest.Unmarshal(m, b)
}
func (m *AddRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRuleRequest.Marshal(b, m, deterministic)
}
func (m *AddRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRuleRequest.Merge(m, src)
}
func (m *AddRuleRequest) XXX_Size() int {
	return xxx_messageInfo_AddRuleRequest.Size(m)
}
func (m *AddRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRuleRequest proto.InternalMessageInfo

func (m *AddRuleRequest) GetRule() *AclRule {
	if m != nil {
		return m.Rule
	}
	return nil
}

// Response body with the newly added ACL rule.
type AddRuleResponse struct {
	Rule                 *AclRule `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRuleResponse) Reset()         { *m = AddRuleResponse{} }
func (m *AddRuleResponse) String() string { return proto.CompactTextString(m) }
func (*AddRuleResponse) ProtoMessage()    {}
func (*AddRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e29e90e62174e322, []int{3}
}

func (m *AddRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRuleResponse.Unmarshal(m, b)
}
func (m *AddRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRuleResponse.Marshal(b, m, deterministic)
}
func (m *AddRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRuleResponse.Merge(m, src)
}
func (m *AddRuleResponse) XXX_Size() int {
	return xxx_messageInfo_AddRuleResponse.Size(m)
}
func (m *AddRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRuleResponse proto.InternalMessageInfo

func (m *AddRuleResponse) GetRule() *AclRule {
	if m != nil {
		return m.Rule
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRulesRequest)(nil), "auth.v1beta1.ListRulesRequest")
	proto.RegisterType((*ListRulesResponse)(nil), "auth.v1beta1.ListRulesResponse")
	proto.RegisterType((*AddRuleRequest)(nil), "auth.v1beta1.AddRuleRequest")
	proto.RegisterType((*AddRuleResponse)(nil), "auth.v1beta1.AddRuleResponse")
}

func init() { proto.RegisterFile("auth/v1beta1/acl_api.proto", fileDescriptor_e29e90e62174e322) }

var fileDescriptor_e29e90e62174e322 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xd4, 0x4f, 0x4c, 0xce, 0x89, 0x4f, 0x2c, 0xc8,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0xc9, 0xe9, 0x41, 0xe5, 0xa4, 0xa4, 0x31,
	0x54, 0x16, 0x95, 0xe6, 0xa4, 0x42, 0x94, 0x2a, 0x09, 0x71, 0x09, 0xf8, 0x64, 0x16, 0x97, 0x04,
	0x95, 0xe6, 0xa4, 0x16, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x39, 0x70, 0x09, 0x22,
	0x89, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x69, 0x73, 0xb1, 0x82, 0xb4, 0x15, 0x4b, 0x30,
	0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x89, 0xea, 0x21, 0xdb, 0xa1, 0xe7, 0x98, 0x9c, 0x03, 0x52, 0x1e,
	0x04, 0x51, 0xa3, 0x64, 0xcd, 0xc5, 0xe7, 0x98, 0x92, 0x02, 0x16, 0x81, 0x98, 0x29, 0xa4, 0xc9,
	0xc5, 0x02, 0x92, 0x92, 0x60, 0x54, 0x60, 0xc4, 0xad, 0x1b, 0xac, 0x44, 0xc9, 0x86, 0x8b, 0x1f,
	0xae, 0x19, 0x6a, 0x39, 0xf1, 0xba, 0x8d, 0xe6, 0x31, 0x72, 0xb1, 0x39, 0x26, 0xe7, 0x38, 0x06,
	0x78, 0x0a, 0xf9, 0x70, 0x71, 0xc2, 0xfd, 0x21, 0x24, 0x87, 0xaa, 0x09, 0xdd, 0xd3, 0x52, 0xf2,
	0x38, 0xe5, 0xa1, 0x6e, 0x70, 0xe3, 0x62, 0x87, 0x3a, 0x4b, 0x48, 0x06, 0xcd, 0x01, 0x28, 0x5e,
	0x95, 0x92, 0xc5, 0x21, 0x0b, 0x31, 0xc7, 0x29, 0x92, 0x4b, 0x3c, 0x33, 0x5f, 0x2f, 0x35, 0xaf,
	0x38, 0x35, 0x31, 0x25, 0x11, 0x45, 0xa9, 0x13, 0x37, 0xc8, 0xe1, 0x05, 0x99, 0x01, 0xa0, 0x98,
	0x09, 0x60, 0x8c, 0xe2, 0x06, 0x49, 0x42, 0xe5, 0x16, 0x31, 0x31, 0x3b, 0x46, 0x44, 0xac, 0x62,
	0xe2, 0x71, 0x04, 0x69, 0x08, 0x33, 0x74, 0x02, 0x09, 0x9e, 0x82, 0x70, 0x63, 0xa0, 0xdc, 0x24,
	0x36, 0x70, 0x9c, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x06, 0x32, 0x06, 0xdc, 0x1c, 0x02,
	0x00, 0x00,
}
