// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/v1beta1/acl_rule.proto

package authv1beta1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Single ACL rule.
type AclRule struct {
	// The subject of the rule. Required.
	Sub string `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	// The subject of the rule. Required. Must be a valid Enseada GUID.
	Obj string `protobuf:"bytes,2,opt,name=obj,proto3" json:"obj,omitempty"`
	// The action of the rule. Required.
	Act                  string   `protobuf:"bytes,3,opt,name=act,proto3" json:"act,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AclRule) Reset()         { *m = AclRule{} }
func (m *AclRule) String() string { return proto.CompactTextString(m) }
func (*AclRule) ProtoMessage()    {}
func (*AclRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_53927126401a53e9, []int{0}
}

func (m *AclRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AclRule.Unmarshal(m, b)
}
func (m *AclRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AclRule.Marshal(b, m, deterministic)
}
func (m *AclRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AclRule.Merge(m, src)
}
func (m *AclRule) XXX_Size() int {
	return xxx_messageInfo_AclRule.Size(m)
}
func (m *AclRule) XXX_DiscardUnknown() {
	xxx_messageInfo_AclRule.DiscardUnknown(m)
}

var xxx_messageInfo_AclRule proto.InternalMessageInfo

func (m *AclRule) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *AclRule) GetObj() string {
	if m != nil {
		return m.Obj
	}
	return ""
}

func (m *AclRule) GetAct() string {
	if m != nil {
		return m.Act
	}
	return ""
}

func init() {
	proto.RegisterType((*AclRule)(nil), "auth.v1beta1.AclRule")
}

func init() { proto.RegisterFile("auth/v1beta1/acl_rule.proto", fileDescriptor_53927126401a53e9) }

var fileDescriptor_53927126401a53e9 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xd4, 0x4f, 0x4c, 0xce, 0x89, 0x2f, 0x2a, 0xcd,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x01, 0x49, 0xea, 0x41, 0x25, 0x95, 0xec,
	0xb9, 0xd8, 0x1d, 0x93, 0x73, 0x82, 0x4a, 0x73, 0x52, 0x85, 0x04, 0xb8, 0x98, 0x8b, 0x4b, 0x93,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x90, 0x48, 0x7e, 0x52, 0x96, 0x04, 0x13,
	0x44, 0x24, 0x3f, 0x29, 0x0b, 0x24, 0x92, 0x98, 0x5c, 0x22, 0xc1, 0x0c, 0x11, 0x49, 0x4c, 0x2e,
	0x71, 0x8a, 0xe2, 0x12, 0xcf, 0xcc, 0xd7, 0x4b, 0xcd, 0x2b, 0x4e, 0x4d, 0x4c, 0x49, 0xd4, 0x43,
	0x36, 0xdb, 0x89, 0x07, 0x6a, 0x72, 0x00, 0xc8, 0xde, 0x00, 0xc6, 0x28, 0x6e, 0x90, 0x2c, 0x54,
	0x72, 0x11, 0x13, 0xb3, 0x63, 0x44, 0xc4, 0x2a, 0x26, 0x1e, 0x47, 0x90, 0x8e, 0x30, 0x43, 0x27,
	0x90, 0xe0, 0x29, 0x08, 0x37, 0x06, 0xca, 0x4d, 0x62, 0x03, 0xbb, 0xd8, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xa9, 0x9f, 0xa9, 0x60, 0xd0, 0x00, 0x00, 0x00,
}
