// Copyright 2019-2020 Enseada authors
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/v1beta1/o_auth_clients_api.proto

package authv1beta1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request body to list all available OAuth clients.
type ListClientsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListClientsRequest) Reset()         { *m = ListClientsRequest{} }
func (m *ListClientsRequest) String() string { return proto.CompactTextString(m) }
func (*ListClientsRequest) ProtoMessage()    {}
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2269de2967d2bebc, []int{0}
}

func (m *ListClientsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClientsRequest.Unmarshal(m, b)
}
func (m *ListClientsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClientsRequest.Marshal(b, m, deterministic)
}
func (m *ListClientsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClientsRequest.Merge(m, src)
}
func (m *ListClientsRequest) XXX_Size() int {
	return xxx_messageInfo_ListClientsRequest.Size(m)
}
func (m *ListClientsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClientsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListClientsRequest proto.InternalMessageInfo

// Response body with a list of all available OAuth clients.
type ListClientsResponse struct {
	Clients              []*OAuthClient `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListClientsResponse) Reset()         { *m = ListClientsResponse{} }
func (m *ListClientsResponse) String() string { return proto.CompactTextString(m) }
func (*ListClientsResponse) ProtoMessage()    {}
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2269de2967d2bebc, []int{1}
}

func (m *ListClientsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClientsResponse.Unmarshal(m, b)
}
func (m *ListClientsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClientsResponse.Marshal(b, m, deterministic)
}
func (m *ListClientsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClientsResponse.Merge(m, src)
}
func (m *ListClientsResponse) XXX_Size() int {
	return xxx_messageInfo_ListClientsResponse.Size(m)
}
func (m *ListClientsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClientsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListClientsResponse proto.InternalMessageInfo

func (m *ListClientsResponse) GetClients() []*OAuthClient {
	if m != nil {
		return m.Clients
	}
	return nil
}

// Request body to get a single OAuth clients.
type GetClientRequest struct {
	// The id of the client to fetch. Required.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientRequest) Reset()         { *m = GetClientRequest{} }
func (m *GetClientRequest) String() string { return proto.CompactTextString(m) }
func (*GetClientRequest) ProtoMessage()    {}
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2269de2967d2bebc, []int{2}
}

func (m *GetClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientRequest.Unmarshal(m, b)
}
func (m *GetClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientRequest.Marshal(b, m, deterministic)
}
func (m *GetClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientRequest.Merge(m, src)
}
func (m *GetClientRequest) XXX_Size() int {
	return xxx_messageInfo_GetClientRequest.Size(m)
}
func (m *GetClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientRequest proto.InternalMessageInfo

func (m *GetClientRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response body with a single OAuth client.
type GetClientResponse struct {
	Client               *OAuthClient `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetClientResponse) Reset()         { *m = GetClientResponse{} }
func (m *GetClientResponse) String() string { return proto.CompactTextString(m) }
func (*GetClientResponse) ProtoMessage()    {}
func (*GetClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2269de2967d2bebc, []int{3}
}

func (m *GetClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientResponse.Unmarshal(m, b)
}
func (m *GetClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientResponse.Marshal(b, m, deterministic)
}
func (m *GetClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientResponse.Merge(m, src)
}
func (m *GetClientResponse) XXX_Size() int {
	return xxx_messageInfo_GetClientResponse.Size(m)
}
func (m *GetClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientResponse proto.InternalMessageInfo

func (m *GetClientResponse) GetClient() *OAuthClient {
	if m != nil {
		return m.Client
	}
	return nil
}

// Request body to create a new OAuth client.
type CreateClientRequest struct {
	// The client to create. Required.
	Client *OAuthClient `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	// Client secret. Optional for public clients.
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientRequest) Reset()         { *m = CreateClientRequest{} }
func (m *CreateClientRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClientRequest) ProtoMessage()    {}
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2269de2967d2bebc, []int{4}
}

func (m *CreateClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientRequest.Unmarshal(m, b)
}
func (m *CreateClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientRequest.Marshal(b, m, deterministic)
}
func (m *CreateClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientRequest.Merge(m, src)
}
func (m *CreateClientRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClientRequest.Size(m)
}
func (m *CreateClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientRequest proto.InternalMessageInfo

func (m *CreateClientRequest) GetClient() *OAuthClient {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *CreateClientRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

// Response body with the newly created OAuth client.
type CreateClientResponse struct {
	Client               *OAuthClient `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateClientResponse) Reset()         { *m = CreateClientResponse{} }
func (m *CreateClientResponse) String() string { return proto.CompactTextString(m) }
func (*CreateClientResponse) ProtoMessage()    {}
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2269de2967d2bebc, []int{5}
}

func (m *CreateClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientResponse.Unmarshal(m, b)
}
func (m *CreateClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientResponse.Marshal(b, m, deterministic)
}
func (m *CreateClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientResponse.Merge(m, src)
}
func (m *CreateClientResponse) XXX_Size() int {
	return xxx_messageInfo_CreateClientResponse.Size(m)
}
func (m *CreateClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientResponse proto.InternalMessageInfo

func (m *CreateClientResponse) GetClient() *OAuthClient {
	if m != nil {
		return m.Client
	}
	return nil
}

// Request body to update an OAuth client.
type UpdateClientRequest struct {
	// The client to update. Required.
	Client               *OAuthClient `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateClientRequest) Reset()         { *m = UpdateClientRequest{} }
func (m *UpdateClientRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateClientRequest) ProtoMessage()    {}
func (*UpdateClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2269de2967d2bebc, []int{6}
}

func (m *UpdateClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClientRequest.Unmarshal(m, b)
}
func (m *UpdateClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClientRequest.Marshal(b, m, deterministic)
}
func (m *UpdateClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClientRequest.Merge(m, src)
}
func (m *UpdateClientRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateClientRequest.Size(m)
}
func (m *UpdateClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClientRequest proto.InternalMessageInfo

func (m *UpdateClientRequest) GetClient() *OAuthClient {
	if m != nil {
		return m.Client
	}
	return nil
}

// Response body with the updated OAuth client.
type UpdateClientResponse struct {
	Client               *OAuthClient `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateClientResponse) Reset()         { *m = UpdateClientResponse{} }
func (m *UpdateClientResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateClientResponse) ProtoMessage()    {}
func (*UpdateClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2269de2967d2bebc, []int{7}
}

func (m *UpdateClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClientResponse.Unmarshal(m, b)
}
func (m *UpdateClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClientResponse.Marshal(b, m, deterministic)
}
func (m *UpdateClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClientResponse.Merge(m, src)
}
func (m *UpdateClientResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateClientResponse.Size(m)
}
func (m *UpdateClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClientResponse proto.InternalMessageInfo

func (m *UpdateClientResponse) GetClient() *OAuthClient {
	if m != nil {
		return m.Client
	}
	return nil
}

// Request body to delete an OAuth client.
type DeleteClientRequest struct {
	// The client to delete. Required.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClientRequest) Reset()         { *m = DeleteClientRequest{} }
func (m *DeleteClientRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteClientRequest) ProtoMessage()    {}
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2269de2967d2bebc, []int{8}
}

func (m *DeleteClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientRequest.Unmarshal(m, b)
}
func (m *DeleteClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientRequest.Marshal(b, m, deterministic)
}
func (m *DeleteClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientRequest.Merge(m, src)
}
func (m *DeleteClientRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteClientRequest.Size(m)
}
func (m *DeleteClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientRequest proto.InternalMessageInfo

func (m *DeleteClientRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response body with the deleted OAuth client.
type DeleteClientResponse struct {
	Client               *OAuthClient `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeleteClientResponse) Reset()         { *m = DeleteClientResponse{} }
func (m *DeleteClientResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteClientResponse) ProtoMessage()    {}
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2269de2967d2bebc, []int{9}
}

func (m *DeleteClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientResponse.Unmarshal(m, b)
}
func (m *DeleteClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientResponse.Marshal(b, m, deterministic)
}
func (m *DeleteClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientResponse.Merge(m, src)
}
func (m *DeleteClientResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteClientResponse.Size(m)
}
func (m *DeleteClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientResponse proto.InternalMessageInfo

func (m *DeleteClientResponse) GetClient() *OAuthClient {
	if m != nil {
		return m.Client
	}
	return nil
}

func init() {
	proto.RegisterType((*ListClientsRequest)(nil), "auth.v1beta1.ListClientsRequest")
	proto.RegisterType((*ListClientsResponse)(nil), "auth.v1beta1.ListClientsResponse")
	proto.RegisterType((*GetClientRequest)(nil), "auth.v1beta1.GetClientRequest")
	proto.RegisterType((*GetClientResponse)(nil), "auth.v1beta1.GetClientResponse")
	proto.RegisterType((*CreateClientRequest)(nil), "auth.v1beta1.CreateClientRequest")
	proto.RegisterType((*CreateClientResponse)(nil), "auth.v1beta1.CreateClientResponse")
	proto.RegisterType((*UpdateClientRequest)(nil), "auth.v1beta1.UpdateClientRequest")
	proto.RegisterType((*UpdateClientResponse)(nil), "auth.v1beta1.UpdateClientResponse")
	proto.RegisterType((*DeleteClientRequest)(nil), "auth.v1beta1.DeleteClientRequest")
	proto.RegisterType((*DeleteClientResponse)(nil), "auth.v1beta1.DeleteClientResponse")
}

func init() {
	proto.RegisterFile("auth/v1beta1/o_auth_clients_api.proto", fileDescriptor_2269de2967d2bebc)
}

var fileDescriptor_2269de2967d2bebc = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x51, 0x4a, 0xeb, 0x40,
	0x14, 0x86, 0x49, 0x0a, 0xbd, 0xf4, 0x34, 0xdc, 0x7b, 0x9d, 0x04, 0xad, 0x79, 0xd0, 0x38, 0x50,
	0xe8, 0x53, 0x4a, 0xda, 0x15, 0xb4, 0x15, 0xb5, 0x52, 0xb0, 0x04, 0x2a, 0x45, 0x84, 0x9a, 0x36,
	0x07, 0x1a, 0x28, 0x4d, 0xec, 0x4c, 0x5d, 0x90, 0x8f, 0xae, 0xc0, 0x35, 0xb8, 0x2a, 0x49, 0x33,
	0x6a, 0x66, 0x4c, 0x0b, 0x16, 0x1f, 0xcf, 0xc9, 0x97, 0xff, 0xff, 0xe1, 0xfc, 0x0c, 0xd4, 0x83,
	0x35, 0x9f, 0x37, 0x9f, 0xbc, 0x29, 0xf2, 0xc0, 0x6b, 0xc6, 0x93, 0x74, 0x9c, 0xcc, 0x16, 0x11,
	0x2e, 0x39, 0x9b, 0x04, 0x49, 0xe4, 0x26, 0xab, 0x98, 0xc7, 0xc4, 0x48, 0xf7, 0xae, 0xc0, 0x6c,
	0x67, 0xfb, 0x4f, 0x19, 0x4f, 0x2d, 0x20, 0x83, 0x88, 0xf1, 0x5e, 0x26, 0xe4, 0xe3, 0xe3, 0x1a,
	0x19, 0xa7, 0xd7, 0x60, 0x4a, 0x5b, 0x96, 0xc4, 0x4b, 0x86, 0xa4, 0x0d, 0x7f, 0x84, 0x63, 0x4d,
	0x73, 0x4a, 0x8d, 0x6a, 0xeb, 0xd8, 0xcd, 0xdb, 0xb9, 0x37, 0x9d, 0x35, 0x9f, 0x67, 0x3f, 0xf9,
	0x1f, 0x24, 0xa5, 0xf0, 0xff, 0x12, 0x85, 0x94, 0xd0, 0x27, 0x7f, 0x41, 0x8f, 0xc2, 0x9a, 0xe6,
	0x68, 0x8d, 0x8a, 0xaf, 0x47, 0x21, 0xbd, 0x80, 0x83, 0x1c, 0x23, 0xdc, 0x3c, 0x28, 0x67, 0x1a,
	0x1b, 0x70, 0xa7, 0x99, 0x00, 0xe9, 0x03, 0x98, 0xbd, 0x15, 0x06, 0x1c, 0x65, 0xbb, 0x9f, 0x2b,
	0x91, 0x43, 0x28, 0x33, 0x9c, 0xad, 0x90, 0xd7, 0xf4, 0x4d, 0x4a, 0x31, 0xd1, 0x3e, 0x58, 0xb2,
	0xc3, 0xfe, 0x61, 0xaf, 0xc0, 0x1c, 0x25, 0xe1, 0x2f, 0x84, 0x4d, 0x43, 0xc9, 0x4a, 0xfb, 0x87,
	0xaa, 0x83, 0x79, 0x8e, 0x0b, 0x54, 0x43, 0xa9, 0x07, 0xeb, 0x83, 0x25, 0x63, 0x7b, 0x3b, 0xb6,
	0x5e, 0x4b, 0xf0, 0x2f, 0xb7, 0x67, 0x9d, 0x61, 0x9f, 0xf8, 0x50, 0xcd, 0xf5, 0x8f, 0x38, 0xb2,
	0xca, 0xf7, 0xc2, 0xda, 0x67, 0x3b, 0x08, 0x11, 0x6d, 0x00, 0x95, 0xcf, 0x8e, 0x91, 0x13, 0x99,
	0x57, 0x0b, 0x6a, 0x9f, 0x6e, 0xfd, 0x2e, 0xd4, 0x46, 0x60, 0xe4, 0x7b, 0x40, 0x94, 0x00, 0x05,
	0x2d, 0xb4, 0xe9, 0x2e, 0xe4, 0x4b, 0x36, 0x7f, 0x49, 0x55, 0xb6, 0xa0, 0x2f, 0xaa, 0x6c, 0x61,
	0x11, 0x46, 0x60, 0xe4, 0xcf, 0xa5, 0xca, 0x16, 0x5c, 0x5c, 0x95, 0x2d, 0xba, 0x76, 0x77, 0x0a,
	0x47, 0x51, 0xec, 0xe2, 0x92, 0x61, 0x10, 0x06, 0x12, 0xdf, 0xb5, 0xa4, 0x93, 0x26, 0xd1, 0x30,
	0x7d, 0x6d, 0x86, 0xda, 0x5d, 0x35, 0xa5, 0x04, 0xf4, 0xac, 0x97, 0x3a, 0xe3, 0xf1, 0x8b, 0x6e,
	0xa4, 0xa8, 0x7b, 0xeb, 0x75, 0xd3, 0xe5, 0x5b, 0x36, 0xde, 0x8b, 0x71, 0x5a, 0xde, 0xbc, 0x53,
	0xed, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x3a, 0xd8, 0xd1, 0x00, 0x05, 0x00, 0x00,
}
