// Copyright 2019-2020 Enseada authors
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/v1beta1/users_api.proto

package authv1beta1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request body to list all registered OAuth users.
type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0450201a6462a0, []int{0}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

// Response body with a list of all registered OAuth users.
type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0450201a6462a0, []int{1}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

// Request body to get a single OAuth user.
type GetUserRequest struct {
	// The username. Required.
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0450201a6462a0, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// Response body with a single OAuth user.
type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0450201a6462a0, []int{3}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// Request body to create a new OAuth user.
type CreateUserRequest struct {
	// The user to create. Required.
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// The user password. Required.
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0450201a6462a0, []int{4}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// Response body with the newly created OAuth user.
type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0450201a6462a0, []int{5}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// Request body to update an OAuth user password.
// The target user is always the current authenticated user.
type UpdateUserPasswordRequest struct {
	// The new password. Required.
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserPasswordRequest) Reset()         { *m = UpdateUserPasswordRequest{} }
func (m *UpdateUserPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserPasswordRequest) ProtoMessage()    {}
func (*UpdateUserPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0450201a6462a0, []int{6}
}

func (m *UpdateUserPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserPasswordRequest.Unmarshal(m, b)
}
func (m *UpdateUserPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserPasswordRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserPasswordRequest.Merge(m, src)
}
func (m *UpdateUserPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserPasswordRequest.Size(m)
}
func (m *UpdateUserPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserPasswordRequest proto.InternalMessageInfo

func (m *UpdateUserPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserPasswordResponse) Reset()         { *m = UpdateUserPasswordResponse{} }
func (m *UpdateUserPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserPasswordResponse) ProtoMessage()    {}
func (*UpdateUserPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0450201a6462a0, []int{7}
}

func (m *UpdateUserPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserPasswordResponse.Unmarshal(m, b)
}
func (m *UpdateUserPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserPasswordResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserPasswordResponse.Merge(m, src)
}
func (m *UpdateUserPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserPasswordResponse.Size(m)
}
func (m *UpdateUserPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserPasswordResponse proto.InternalMessageInfo

// Request body to delete an OAuth user.
type DeleteUserRequest struct {
	// The username of the user to delete. Required.
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0450201a6462a0, []int{8}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// Response body with the deleted OAuth user.
type DeleteUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0450201a6462a0, []int{9}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*ListUsersRequest)(nil), "auth.v1beta1.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "auth.v1beta1.ListUsersResponse")
	proto.RegisterType((*GetUserRequest)(nil), "auth.v1beta1.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "auth.v1beta1.GetUserResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "auth.v1beta1.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "auth.v1beta1.CreateUserResponse")
	proto.RegisterType((*UpdateUserPasswordRequest)(nil), "auth.v1beta1.UpdateUserPasswordRequest")
	proto.RegisterType((*UpdateUserPasswordResponse)(nil), "auth.v1beta1.UpdateUserPasswordResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "auth.v1beta1.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "auth.v1beta1.DeleteUserResponse")
}

func init() { proto.RegisterFile("auth/v1beta1/users_api.proto", fileDescriptor_7a0450201a6462a0) }

var fileDescriptor_7a0450201a6462a0 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0x4d, 0xe1, 0xfb, 0x81, 0x0b, 0xdf, 0xa7, 0xcc, 0x06, 0x9c, 0xa0, 0x92, 0x59, 0x68, 0x17,
	0xa6, 0x04, 0x5c, 0x18, 0x13, 0x5c, 0x80, 0x46, 0x63, 0x42, 0x62, 0x43, 0x82, 0x12, 0x35, 0x31,
	0x43, 0xb8, 0xd1, 0x26, 0x4a, 0x6b, 0xa7, 0xe8, 0xfb, 0xb8, 0xd4, 0x37, 0xf1, 0xa9, 0xcc, 0xb4,
	0x63, 0xe9, 0x0f, 0x55, 0x59, 0xde, 0x39, 0xe7, 0xdc, 0x73, 0x67, 0xce, 0x6d, 0xa1, 0xce, 0x67,
	0xde, 0x5d, 0xf3, 0xa9, 0x35, 0x46, 0x8f, 0xb7, 0x9a, 0x33, 0x81, 0xae, 0xb8, 0xe1, 0x8e, 0x65,
	0x38, 0xae, 0xed, 0xd9, 0xa4, 0x2c, 0x51, 0x43, 0xa1, 0xb4, 0x9a, 0xe2, 0x06, 0x34, 0x46, 0x60,
	0xb5, 0x6f, 0x09, 0x6f, 0x28, 0xd5, 0x03, 0x7c, 0x9c, 0xa1, 0xf0, 0xd8, 0x01, 0x54, 0x22, 0x67,
	0xc2, 0xb1, 0xa7, 0x02, 0x89, 0x0e, 0xbf, 0x7d, 0x8b, 0x9a, 0xd6, 0xc8, 0xeb, 0xa5, 0x36, 0x31,
	0xa2, 0xfd, 0x0d, 0xc9, 0x1d, 0x04, 0x04, 0xb6, 0x03, 0xff, 0x4f, 0xd0, 0x57, 0xab, 0x86, 0x84,
	0x42, 0x41, 0x42, 0x53, 0xfe, 0x80, 0x35, 0xad, 0xa1, 0xe9, 0xc5, 0x41, 0x58, 0xb3, 0x7d, 0x58,
	0x09, 0xd9, 0xca, 0x6a, 0x0b, 0x7e, 0x49, 0xd8, 0xa7, 0x2e, 0x76, 0xf2, 0x71, 0x76, 0x01, 0x95,
	0x43, 0x17, 0xb9, 0x87, 0x51, 0xaf, 0x1f, 0x8a, 0xe5, 0x4c, 0x0e, 0x17, 0xe2, 0xd9, 0x76, 0x27,
	0xb5, 0x5c, 0x30, 0xd3, 0x67, 0xcd, 0x3a, 0x40, 0xa2, 0x8d, 0x97, 0x1c, 0x6b, 0x0f, 0xd6, 0x86,
	0xce, 0x44, 0xa9, 0x4d, 0xd5, 0x33, 0xf2, 0x14, 0xa1, 0xad, 0x96, 0xb0, 0xad, 0x03, 0x5d, 0x24,
	0x0c, 0xec, 0x59, 0x13, 0x2a, 0x47, 0x78, 0x8f, 0xf1, 0xdb, 0x7e, 0xf5, 0xb2, 0x1d, 0x20, 0x51,
	0xc1, 0x72, 0xb7, 0x68, 0xbf, 0xe5, 0xa1, 0xe0, 0x6f, 0x40, 0xd7, 0x3c, 0x25, 0x7d, 0x28, 0x86,
	0x1b, 0x41, 0x36, 0xe2, 0x9a, 0xe4, 0xfa, 0xd0, 0xcd, 0x4c, 0x5c, 0x8d, 0x70, 0x0c, 0x7f, 0x55,
	0xe4, 0xa4, 0x1e, 0xe7, 0xc6, 0xf7, 0x86, 0xae, 0x67, 0xa0, 0xaa, 0xcf, 0x19, 0xc0, 0x3c, 0x26,
	0x92, 0xb0, 0x4d, 0x6d, 0x06, 0x6d, 0x64, 0x13, 0x54, 0xc3, 0x5b, 0x20, 0xe9, 0x00, 0xc8, 0x76,
	0xe2, 0x8d, 0xb2, 0xb2, 0xa5, 0xfa, 0xf7, 0xc4, 0xf9, 0xe4, 0xf3, 0x68, 0x92, 0x93, 0xa7, 0x52,
	0x4e, 0x4e, 0x9e, 0x4e, 0xb5, 0x77, 0x05, 0x55, 0xcb, 0x36, 0x70, 0x2a, 0x90, 0x4f, 0x78, 0x8c,
	0xdd, 0xfb, 0x17, 0xa4, 0xe8, 0x58, 0xa6, 0xfc, 0xe0, 0x4d, 0xed, 0xb2, 0x24, 0x61, 0x85, 0xbe,
	0xe4, 0xf2, 0xdd, 0xd1, 0xe8, 0x35, 0x57, 0xee, 0x4a, 0xc9, 0x79, 0xab, 0x27, 0x0f, 0xdf, 0x83,
	0xf2, 0x5a, 0x95, 0xe3, 0x3f, 0xfe, 0xaf, 0x62, 0xf7, 0x23, 0x00, 0x00, 0xff, 0xff, 0xae, 0x77,
	0x15, 0x4e, 0x71, 0x04, 0x00, 0x00,
}
