[workspace]
members = [
    # New stuff
    "api_server",
    "api",
    "users",
    "controller_runtime",

    # Old Stuff
    "old_api",
    "couchdb",
    "lib",
    "old_users",
    "observability",
    "rbac",
    "oci",
    "maven",
    "oauth",
#    "server",
]

[profile.release]
lto = "thin"
