#!/bin/sh

set -e

echo "running pre-commit hook"

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$" || true)

if [[ "$STAGED_GO_FILES" = "" ]]; then
  echo "nothing to do"
  exit 0
fi

make fmt
make vet
make imports
make update-license

git add .

echo "done"

exit 0