[package]
name = "auth"
version = "0.1.0"
edition = "2021"

[dependencies]
futon = { path = "../futon" }

serde = { version = "1", features = ["derive"] }
schemars = "0.8.8"
axum = "0.5"
libapi = { path = "../libapi" }
tracing = "0.1.32"
thiserror = "1"
