// Code generated by protoc-gen-go. DO NOT EDIT.
// source: maven/v1beta1/maven_api.proto

package mavenv1beta1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request body to list all available Maven repositories.
type ListReposRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReposRequest) Reset()         { *m = ListReposRequest{} }
func (m *ListReposRequest) String() string { return proto.CompactTextString(m) }
func (*ListReposRequest) ProtoMessage()    {}
func (*ListReposRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d05b97ef3a7f10c9, []int{0}
}

func (m *ListReposRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReposRequest.Unmarshal(m, b)
}
func (m *ListReposRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReposRequest.Marshal(b, m, deterministic)
}
func (m *ListReposRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReposRequest.Merge(m, src)
}
func (m *ListReposRequest) XXX_Size() int {
	return xxx_messageInfo_ListReposRequest.Size(m)
}
func (m *ListReposRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReposRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListReposRequest proto.InternalMessageInfo

// Response body with a list of all available Maven repositories.
type ListReposResponse struct {
	Repos                []*Repo  `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReposResponse) Reset()         { *m = ListReposResponse{} }
func (m *ListReposResponse) String() string { return proto.CompactTextString(m) }
func (*ListReposResponse) ProtoMessage()    {}
func (*ListReposResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d05b97ef3a7f10c9, []int{1}
}

func (m *ListReposResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReposResponse.Unmarshal(m, b)
}
func (m *ListReposResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReposResponse.Marshal(b, m, deterministic)
}
func (m *ListReposResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReposResponse.Merge(m, src)
}
func (m *ListReposResponse) XXX_Size() int {
	return xxx_messageInfo_ListReposResponse.Size(m)
}
func (m *ListReposResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReposResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListReposResponse proto.InternalMessageInfo

func (m *ListReposResponse) GetRepos() []*Repo {
	if m != nil {
		return m.Repos
	}
	return nil
}

// Request body to retrieve a Maven repository.
type GetRepoRequest struct {
	// ID of the repository to retrieve. Required.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRepoRequest) Reset()         { *m = GetRepoRequest{} }
func (m *GetRepoRequest) String() string { return proto.CompactTextString(m) }
func (*GetRepoRequest) ProtoMessage()    {}
func (*GetRepoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d05b97ef3a7f10c9, []int{2}
}

func (m *GetRepoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRepoRequest.Unmarshal(m, b)
}
func (m *GetRepoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRepoRequest.Marshal(b, m, deterministic)
}
func (m *GetRepoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRepoRequest.Merge(m, src)
}
func (m *GetRepoRequest) XXX_Size() int {
	return xxx_messageInfo_GetRepoRequest.Size(m)
}
func (m *GetRepoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRepoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRepoRequest proto.InternalMessageInfo

func (m *GetRepoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response body with the requested Maven repository.
type GetRepoResponse struct {
	Repo                 *Repo    `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRepoResponse) Reset()         { *m = GetRepoResponse{} }
func (m *GetRepoResponse) String() string { return proto.CompactTextString(m) }
func (*GetRepoResponse) ProtoMessage()    {}
func (*GetRepoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d05b97ef3a7f10c9, []int{3}
}

func (m *GetRepoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRepoResponse.Unmarshal(m, b)
}
func (m *GetRepoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRepoResponse.Marshal(b, m, deterministic)
}
func (m *GetRepoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRepoResponse.Merge(m, src)
}
func (m *GetRepoResponse) XXX_Size() int {
	return xxx_messageInfo_GetRepoResponse.Size(m)
}
func (m *GetRepoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRepoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRepoResponse proto.InternalMessageInfo

func (m *GetRepoResponse) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

// Request body to create a new Maven repository.
type CreateRepoRequest struct {
	// The repository Group ID. Required.
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// The repository Artifact ID. Required.
	ArtifactId           string   `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRepoRequest) Reset()         { *m = CreateRepoRequest{} }
func (m *CreateRepoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRepoRequest) ProtoMessage()    {}
func (*CreateRepoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d05b97ef3a7f10c9, []int{4}
}

func (m *CreateRepoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRepoRequest.Unmarshal(m, b)
}
func (m *CreateRepoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRepoRequest.Marshal(b, m, deterministic)
}
func (m *CreateRepoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRepoRequest.Merge(m, src)
}
func (m *CreateRepoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRepoRequest.Size(m)
}
func (m *CreateRepoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRepoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRepoRequest proto.InternalMessageInfo

func (m *CreateRepoRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *CreateRepoRequest) GetArtifactId() string {
	if m != nil {
		return m.ArtifactId
	}
	return ""
}

// Response body with the newly created Maven repository.
type CreateRepoResponse struct {
	Repo                 *Repo    `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRepoResponse) Reset()         { *m = CreateRepoResponse{} }
func (m *CreateRepoResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRepoResponse) ProtoMessage()    {}
func (*CreateRepoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d05b97ef3a7f10c9, []int{5}
}

func (m *CreateRepoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRepoResponse.Unmarshal(m, b)
}
func (m *CreateRepoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRepoResponse.Marshal(b, m, deterministic)
}
func (m *CreateRepoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRepoResponse.Merge(m, src)
}
func (m *CreateRepoResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRepoResponse.Size(m)
}
func (m *CreateRepoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRepoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRepoResponse proto.InternalMessageInfo

func (m *CreateRepoResponse) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

// Request body to retrieve a Maven repository.
type DeleteRepoRequest struct {
	// ID of the repository to retrieve. Required.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRepoRequest) Reset()         { *m = DeleteRepoRequest{} }
func (m *DeleteRepoRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRepoRequest) ProtoMessage()    {}
func (*DeleteRepoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d05b97ef3a7f10c9, []int{6}
}

func (m *DeleteRepoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRepoRequest.Unmarshal(m, b)
}
func (m *DeleteRepoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRepoRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRepoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRepoRequest.Merge(m, src)
}
func (m *DeleteRepoRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRepoRequest.Size(m)
}
func (m *DeleteRepoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRepoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRepoRequest proto.InternalMessageInfo

func (m *DeleteRepoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response body with the requested Maven repository.
type DeleteRepoResponse struct {
	Repo                 *Repo    `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRepoResponse) Reset()         { *m = DeleteRepoResponse{} }
func (m *DeleteRepoResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRepoResponse) ProtoMessage()    {}
func (*DeleteRepoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d05b97ef3a7f10c9, []int{7}
}

func (m *DeleteRepoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRepoResponse.Unmarshal(m, b)
}
func (m *DeleteRepoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRepoResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRepoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRepoResponse.Merge(m, src)
}
func (m *DeleteRepoResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRepoResponse.Size(m)
}
func (m *DeleteRepoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRepoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRepoResponse proto.InternalMessageInfo

func (m *DeleteRepoResponse) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

func init() {
	proto.RegisterType((*ListReposRequest)(nil), "maven.v1beta1.ListReposRequest")
	proto.RegisterType((*ListReposResponse)(nil), "maven.v1beta1.ListReposResponse")
	proto.RegisterType((*GetRepoRequest)(nil), "maven.v1beta1.GetRepoRequest")
	proto.RegisterType((*GetRepoResponse)(nil), "maven.v1beta1.GetRepoResponse")
	proto.RegisterType((*CreateRepoRequest)(nil), "maven.v1beta1.CreateRepoRequest")
	proto.RegisterType((*CreateRepoResponse)(nil), "maven.v1beta1.CreateRepoResponse")
	proto.RegisterType((*DeleteRepoRequest)(nil), "maven.v1beta1.DeleteRepoRequest")
	proto.RegisterType((*DeleteRepoResponse)(nil), "maven.v1beta1.DeleteRepoResponse")
}

func init() { proto.RegisterFile("maven/v1beta1/maven_api.proto", fileDescriptor_d05b97ef3a7f10c9) }

var fileDescriptor_d05b97ef3a7f10c9 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdf, 0x4e, 0xea, 0x40,
	0x10, 0xc6, 0xd3, 0x72, 0xce, 0x01, 0x86, 0x03, 0xe7, 0xb0, 0xde, 0xd4, 0x26, 0x48, 0xad, 0x17,
	0xe2, 0x4d, 0x09, 0x78, 0x67, 0x82, 0x89, 0x68, 0xa2, 0x24, 0xa2, 0xd8, 0x0b, 0x43, 0x8c, 0x09,
	0x59, 0xec, 0x68, 0x9a, 0x28, 0xad, 0xdd, 0x85, 0x07, 0xf2, 0xd2, 0x47, 0xe1, 0xa9, 0xcc, 0x6e,
	0x57, 0xe8, 0x9f, 0x60, 0xc2, 0xe5, 0xcc, 0xf7, 0x9b, 0x6f, 0x66, 0x67, 0xb2, 0xd0, 0x78, 0xa3,
	0x0b, 0x9c, 0xb5, 0x17, 0x9d, 0x29, 0x72, 0xda, 0x69, 0xcb, 0x68, 0x42, 0x43, 0xdf, 0x09, 0xa3,
	0x80, 0x07, 0xa4, 0x2a, 0x13, 0x8e, 0x92, 0x4d, 0x23, 0x4d, 0x47, 0x18, 0x06, 0x31, 0x68, 0x13,
	0xf8, 0x7f, 0xed, 0x33, 0xee, 0x62, 0x18, 0x30, 0x17, 0xdf, 0xe7, 0xc8, 0xb8, 0x7d, 0x0a, 0xf5,
	0x44, 0x8e, 0x85, 0xc1, 0x8c, 0x21, 0x39, 0x82, 0xdf, 0xa2, 0x8c, 0x19, 0x9a, 0x55, 0x68, 0x55,
	0xba, 0x3b, 0x4e, 0xaa, 0x83, 0x23, 0x60, 0x37, 0x26, 0x6c, 0x0b, 0x6a, 0x97, 0x28, 0xcb, 0x95,
	0x23, 0xa9, 0x81, 0xee, 0x7b, 0x86, 0x66, 0x69, 0xad, 0xb2, 0xab, 0xfb, 0x9e, 0x7d, 0x02, 0xff,
	0x56, 0x84, 0xf2, 0x3f, 0x84, 0x5f, 0xa2, 0x5a, 0x42, 0x1b, 0xec, 0x25, 0x60, 0xdf, 0x42, 0xfd,
	0x3c, 0x42, 0xca, 0x31, 0xd9, 0x60, 0x17, 0x4a, 0x2f, 0x51, 0x30, 0x0f, 0x27, 0xab, 0x36, 0x45,
	0x19, 0x0f, 0x3c, 0xd2, 0x84, 0x0a, 0x8d, 0xb8, 0xff, 0x4c, 0x9f, 0xb8, 0x50, 0x75, 0xa9, 0xc2,
	0x77, 0x6a, 0xe0, 0xd9, 0x3d, 0x20, 0x49, 0xc3, 0x6d, 0xe7, 0x39, 0x80, 0xfa, 0x05, 0xbe, 0x62,
	0x7a, 0x9e, 0xec, 0x83, 0x7b, 0x40, 0x92, 0xd0, 0x96, 0x3d, 0xba, 0x4b, 0x1d, 0x4a, 0x43, 0x21,
	0x9e, 0x8d, 0x06, 0xe4, 0x06, 0xca, 0xab, 0xf3, 0x90, 0x66, 0xa6, 0x28, 0x7b, 0x4c, 0xd3, 0xda,
	0x0c, 0xa8, 0x29, 0xae, 0xa0, 0xa8, 0x8e, 0x41, 0x1a, 0x19, 0x38, 0x7d, 0x46, 0x73, 0x6f, 0x93,
	0xac, 0x9c, 0xee, 0x00, 0xd6, 0x9b, 0x24, 0xd9, 0xce, 0xb9, 0xab, 0x99, 0xfb, 0x3f, 0x10, 0x6b,
	0xcb, 0xf5, 0xe2, 0x72, 0x96, 0xb9, 0xc5, 0xe7, 0x2c, 0xf3, 0x5b, 0xef, 0x4f, 0xc0, 0xf0, 0x03,
	0x07, 0x67, 0x0c, 0xa9, 0x47, 0xd3, 0x78, 0xbf, 0x1a, 0x6f, 0x39, 0xf4, 0x47, 0xe2, 0x77, 0x8c,
	0xb4, 0x87, 0xbf, 0x52, 0x57, 0xf2, 0x87, 0x5e, 0x18, 0x8e, 0xc7, 0x9f, 0x7a, 0x4c, 0x39, 0xf7,
	0x9d, 0xbe, 0xc8, 0x2e, 0x55, 0xfc, 0xa8, 0xe2, 0xe9, 0x1f, 0xf9, 0xb5, 0x8e, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xa5, 0xfe, 0xad, 0x63, 0xa4, 0x03, 0x00, 0x00,
}
