// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta/v1beta1/metadata.proto

package metav1beta1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Generic object metadata.
type Metadata struct {
	// The object name.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_532be1e52df522fe, []int{0}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Metadata)(nil), "meta.v1beta1.Metadata")
}

func init() { proto.RegisterFile("meta/v1beta1/metadata.proto", fileDescriptor_532be1e52df522fe) }

var fileDescriptor_532be1e52df522fe = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0x4d, 0x2d, 0x49,
	0xd4, 0x2f, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0xd4, 0x07, 0x71, 0x52, 0x12, 0x4b, 0x12, 0xf5,
	0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x78, 0x40, 0x7c, 0x3d, 0xa8, 0xa4, 0x92, 0x1c, 0x17, 0x87,
	0x2f, 0x54, 0x5e, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x33, 0x08, 0xcc, 0x76, 0x8a, 0xe6, 0x12, 0xcf, 0xcc, 0xd7, 0x4b, 0xcd, 0x2b, 0x4e, 0x4d, 0x4c,
	0x49, 0xd4, 0x43, 0xd6, 0xea, 0xc4, 0x0b, 0xd3, 0x18, 0x00, 0x32, 0x37, 0x80, 0x31, 0x8a, 0x1b,
	0x24, 0x0d, 0x95, 0x5d, 0xc4, 0xc4, 0xec, 0x1b, 0x11, 0xb1, 0x8a, 0x89, 0x07, 0xa4, 0x48, 0x2f,
	0xcc, 0xd0, 0x09, 0x24, 0x78, 0x0a, 0xc2, 0x8d, 0x81, 0x72, 0x93, 0xd8, 0xc0, 0x2e, 0x32, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x57, 0xaf, 0x1e, 0xd0, 0xb0, 0x00, 0x00, 0x00,
}
